image: nikolaik/python-nodejs

stages:
  - build
  - deploy

build:
  stage: build

  environment:
    name: production

  before_script:
    - npm install

  script:
    - npm run build

  only:
    - master

  artifacts:
    expire_in: 4 days
    paths:
      - build

deploy:
  stage: deploy

  environment:
    name: production

  script:
    - pip install awscli
    - npm run deploy-dev

  only:
    - master
