export const noteLineDetails: {
  [index: string]: string;
} = {
  "req": "REQ-",
  "name": "Clinician name/Extension: ",
  "lob": "LOB: ",
  "service": "Service: ",
  "drugRequest": "Drug Request: ",
  "addInfo": "Additional Info Requested",
  "code": "Suspended codes: ",
  "pend": "Suspension: ",
  "policyString": "Medical Policy/Criteria: ",
  "pa": "PA on file: ",
  "claimHistory": "Claim history: ",
  "benefits": "Benefits",
  "summary": "Case summary: ",
  "exCircum": "Extenuating Circumstances: ",
  "criteriaMet": "Criteria Met: ",
  "criteriaNotMet": "Criteria Not Met: ",
  "deter": "Determination: ",
  "related": "Related UM requests: ",
  "route": "Route: ",
  "decisionReq": "Request # utilized to apply decision: ",
  "referral": "Primary Reason for Referral: ",
  "from": "From date: ",
  "to": "To date: ",
  "mdNote": "NOTE: Medical Director Only: Please refer to the following section of plan document: What Is Not Covered or General Exclusions.",
  "referReasons": "",
  "misrouteRationale": "Rationale: ",
  "misrouteDeter": "Determination: Claim referred in error",
};
