export {default as Name} from './Name';
export {default as Req} from './Req';
export {default as Age} from './Age';
export {default as Dos} from './Dos';
export {default as Diagnosis} from './Diagnosis';
export {default as Provider} from './Provider';
export {default as Par} from './Par';
export {default as Summary} from './Summary';
export {default as ClaimHistory} from './ClaimHistory';