const switches = {
  "allMet": ["exCircum"],
  "claimType": ["noPricingRationale"],
  "code": ["service"],
  "covidRelated": ["summary"],
  "daysOff": [],
  "deter": ["exCircum", "allMet", "code", "rationale", "specficType"],
  "lob": ["claimType"],
  "name": [],
  "paDiagnosis": ["diagnosis"],
  "paDeter": ["deter", "disableAllMet"],
  "paMatch": ["deter", "disableAllMet"],
  "paProvider": ["provider"],
  "policy": ["info", "interqual", "deter", "rationale", "exCircum"],
  "rationale": ["exCircum"],
  "relatedInfo": ["rationale"],
  "serviceType": ["drugReview", "specificType", "noPricingRationale"],
  "special": ["claimSystem"],
  "shiftHours": [],

}